{{- range .Values.SecretProviderClass }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  provider: {{ .provider }}
  parameters:
    roleName: {{ .parameters.roleName | quote }}
    objects: |
      {{- .parameters.objects | nindent 6 }}
{{- end }}
