{{- range .Values.users }}
{{- if eq .service_account.create "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .service_account.name }}
  namespace: {{ .service_account.namespace }}
{{- end }}
{{- end }}
