SecretProviderClass:
- name: stepshop-aps-envs
  namespace: stepshop-aps
  provider: vault
  parameters:
    roleName: "stepora-eks-v2-stepshop-aps-app-role"
    objects: |
      - objectName: "application.env"
        secretPath: "stepora-secrets/data/b2b/production/stepshop/env"
        secretKey: "app-env"

- name: stepshop-aps-certs-msk
  namespace: stepshop-aps
  provider: vault
  parameters:
    roleName: "stepora-eks-v2-stepshop-aps-app-role"
    objects: |
      - objectName: "aws-truststore.cert"
        secretPath: "stepora-secrets/data/b2b/production/stepshop/certs-msk"
        secretKey: "aws-truststore.cert"
      - objectName: "sslcert.crt"
        secretPath: "stepora-secrets/data/b2b/production/stepshop/certs-msk"
        secretKey: "sslcert.crt"
      - objectName: "sslcert.key"
        secretPath: "stepora-secrets/data/b2b/production/stepshop/certs-msk"
        secretKey: "sslcert.key"