apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
    tier: cron
spec:
  selector:
    app: {{ .Values.app_name }}
    tier: cron
  ports:
    - port: {{ .Values.service.default.port }}
      protocol: {{ .Values.service.default.protocol }}
      targetPort: {{ .Values.service.default.targetPort }}
