namespace: 'stepshop'

app_name: 'stepshop'
environment: 'production'

service:
  name: 'stepshop-worker'
  default:
    port: 8000
    protocol: 'TCP'
    targetPort: 8000

hpa:
  name: 'stepshop-worker-hpa'
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

pdb:
  name: 'stepshop-worker-pdb'
  minAvailable: 80%

deployment:
  name: 'stepshop-worker-deployment'
  replicas: 1
  maxSurge: 100%
  maxUnavailable: 0%
  serviceAccountName: 'stepora-stepshop-vault'

  containers:
    default:
      name: 'worker'
      imagePullPolicy: 'Always'
      image: '211535858832.dkr.ecr.ap-south-1.amazonaws.com/production/stepora/stepshop/backend-app:[BUILD_TAG]'
      command: '["sh", "-c", "/bin/cp -f /vault/secrets/application.env /etc/profile.d/application-env.sh ; source /etc/profile.d/application-env.sh ; sh /stepora/deployment/app/worker-entrypoint.sh"]'
      memory:
        requests: 300Mi
        limits: 400Mi
      cpu:
        requests: 50m
      volumeMounts:
        - mountPath: '/stepora/logs/'
          name: 'stepora-stepshop-production-worker-logs'
        - name: 'stepshop-app-env-volume'
          mountPath: "/vault/secrets"
        - name: 'stepshop-certs-msk-volume'
          mountPath: "/stepora/certs/msk"

  volumes:
    - name: 'stepora-stepshop-production-worker-logs'
      hostPath:
        path: '/home/ec2-user/stepora-logs/stepora-stepshop-production/worker'
    - name: 'stepshop-app-env-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "stepshop-envs"
    - name: 'stepshop-certs-msk-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "stepshop-certs-msk"

  nodeSelector:
    key: 'karpenter.sh/nodepool'
    value: 'default'

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: 'topology.kubernetes.io/zone'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'stepshop'
          tier: worker
    - maxSkew: 1
      topologyKey: 'kubernetes.io/hostname'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'stepshop'
          tier: worker

  priorityClassName: 'production-medium'
  terminationGracePeriodSeconds: 60
