namespace: 'stepshop'

app_name: 'stepshop'

job:
  name: 'stepshop-collectstatic-job'
  backoffLimit: 0
  activeDeadlineSeconds: 900
  ttlSecondsAfterFinished: 60
  serviceAccountName: 'stepora-stepshop-vault'

  containers:
    - name: 'collectstatic'
      imagePullPolicy: 'Always'
      image: '211535858832.dkr.ecr.ap-south-1.amazonaws.com/production/stepora/stepshop/backend-app:[BUILD_TAG]'
      command: '["sh", "-c", "/bin/cp -f /vault/secrets/application.env /etc/profile.d/application-env.sh ; source /etc/profile.d/application-env.sh ; python3.7 manage.py collectstatic --no-input >> /stepora/logs/app.out.collectstatic.log 2>&1"]'
      memory:
        requests: 1000Mi
        limits: 1500Mi
      cpu:
        requests: 1000m
        limits: 1500m
      volumeMounts:
        - mountPath: '/stepora/logs/'
          name: 'stepora-stepshop-production-collectstatic-logs'
        - name: 'stepshop-app-env-volume'
          mountPath: "/vault/secrets"
        - name: 'stepshop-certs-msk-volume'
          mountPath: "/stepora/certs/msk"

  volumes:
    - name: 'stepora-stepshop-production-collectstatic-logs'
      hostPath:
        path: '/home/ec2-user/stepora-logs/stepora-stepshop-production/collectstatic'
    - name: 'stepshop-app-env-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "stepshop-envs"
    - name: 'stepshop-certs-msk-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "stepshop-certs-msk"

  nodeSelector:
    key: 'karpenter.sh/nodepool'
    value: 'default'
  priorityClassName: 'production-critical'
  restartPolicy: 'Never'
  terminationGracePeriodSeconds: 120

