namespace: 'stepshop'

app_name: 'stepshop'
environment: 'production'

service:
  name: 'stepshop-app'
  default:
    port: 8000
    protocol: 'TCP'
    targetPort: 8000

hpa:
  name: 'stepshop-app-hpa'
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

pdb:
  name: 'stepshop-app-pdb'
  minAvailable: 50%

deployment:
  name: 'stepshop-app-deployment'
  replicas: 5
  maxSurge: 100%
  maxUnavailable: 50%
  serviceAccountName: 'stepora-stepshop-vault'

  containers:
    default:
      name: 'app'
      imagePullPolicy: 'Always'
      image: '211535858832.dkr.ecr.ap-south-1.amazonaws.com/production/stepora/stepshop/backend-app:[BUILD_TAG]'
      command:
        - sh
        - -c
        - /bin/cp -f /vault/secrets/application.env /etc/profile.d/application-env.sh ; source /etc/profile.d/application-env.sh ; sh /stepora/deployment/app/app-entrypoint.sh
      env:
        - name: 'DJANGO_SETTINGS_MODUL'
          value: 'DJANGO_SETTINGS_MODULE'
      port: 8000
      memory:
        requests: 400Mi
        limits: 600Mi
      cpu:
        requests: 50m
      health:
        path: '/health'
        port: 8000
        scheme: 'HTTP'
      startupProbe:
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 7
      readinessProbe:
        initialDelaySeconds: 0
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      livenessProbe:
        initialDelaySeconds: 0
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      volumeMounts:
        - mountPath: '/stepora/logs/'
          name: 'stepora-stepshop-production-app-logs'
        - name: 'stepshop-app-env-volume'
          mountPath: "/vault/secrets"
        - name: 'stepshop-certs-msk-volume'
          mountPath: "/stepora/certs/msk"

  volumes:
    - name: 'stepora-stepshop-production-app-logs'
      hostPath:
        path: '/home/ec2-user/stepora-logs/stepora-stepshop-production/app'
    - name: 'stepshop-app-env-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "stepshop-envs"
    - name: 'stepshop-certs-msk-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "stepshop-certs-msk"

  nodeSelector:
    key: 'karpenter.sh/nodepool'
    value: 'default'

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: 'topology.kubernetes.io/zone'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'stepshop'
          tier: app
    - maxSkew: 1
      topologyKey: 'kubernetes.io/hostname'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'stepshop'
          tier: app

  priorityClassName: 'production-medium'
  terminationGracePeriodSeconds: 60
